### ISSUE TITLE
Package can not be installed on Darwin and Linux-armv6l (serialport@5.0.0)

### ISSUE THREAD

**Issue by DJFliX** [smart-home-technology/at-commander#2]
Full yarn output:
```
pi@raspberrypi:~/hekkie $ yarn
yarn install v1.12.3
warning package.json: No license field
warning No license field
[1/4] Resolving packages...
warning Lockfile has incorrect entry for "serialport@5.0.0". Ignoring it.
warning at-commander > serialport > node-pre-gyp > hawk > hoek@2.16.3: This version is no longer maintained. Please upgrade to the latest version.
warning at-commander > serialport > node-pre-gyp > hawk > boom@2.10.1: This version is no longer maintained. Please upgrade to the latest version.
warning at-commander > serialport > node-pre-gyp > hawk > boom > hoek@2.16.3: This version is no longer maintained. Please upgrade to the latest version.
warning at-commander > serialport > node-pre-gyp > hawk > cryptiles@2.0.5: This version is no longer maintained. Please upgrade to the latest version.
warning at-commander > serialport > node-pre-gyp > hawk > cryptiles > boom@2.10.1: This version is no longer maintained. Please upgrade to the latest version.
warning at-commander > serialport > node-pre-gyp > hawk > sntp > hoek@2.16.3: This version is no longer maintained. Please upgrade to the latest version.
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
error /home/pi/hekkie/node_modules/serialport: Command failed.
Exit code: 1
Command: node-pre-gyp install --fallback-to-build
Arguments: 
Directory: /home/pi/hekkie/node_modules/serialport
Output:
node-pre-gyp info it worked if it ends with ok
node-pre-gyp info using node-pre-gyp@0.6.39
node-pre-gyp info using node@11.4.0 | linux | arm
node-pre-gyp info check checked for "/home/pi/hekkie/node_modules/serialport/build/Release/serialport.node" (not found)
node-pre-gyp http GET https://github.com/EmergingTechnologyAdvisors/node-serialport/releases/download/5.0.0/serialport-v5.0.0-node-v67-linux-arm.tar.gz
node-pre-gyp http 404 https://github.com/EmergingTechnologyAdvisors/node-serialport/releases/download/5.0.0/serialport-v5.0.0-node-v67-linux-arm.tar.gz
node-pre-gyp ERR! Tried to download(404): https://github.com/EmergingTechnologyAdvisors/node-serialport/releases/download/5.0.0/serialport-v5.0.0-node-v67-linux-arm.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for serialport@5.0.0 and node@11.4.0 (node-v67 ABI, glibc) (falling back to source compile with node-gyp) 
node-pre-gyp http 404 status code downloading tarball https://github.com/EmergingTechnologyAdvisors/node-serialport/releases/download/5.0.0/serialport-v5.0.0-node-v67-linux-arm.tar.gz 
node-pre-gyp ERR! Tried to download(undefined): https://github.com/EmergingTechnologyAdvisors/node-serialport/releases/download/5.0.0/serialport-v5.0.0-node-v67-linux-arm.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for serialport@5.0.0 and node@11.4.0 (node-v67 ABI, glibc) (falling back to source compile with node-gyp) 
node-pre-gyp http Connection closed while downloading tarball file 
gypgyp  info infoit worked if it ends with ok
 it worked if it ends with ok
gypgyp info using  node-gyp@3.8.0
info using node-gyp@3.8.0
gyp info using node@11.4.0 | linux | arm
gyp info using node@11.4.0 | linux | arm
gypgyp info  infook  
ok 
gyp info it worked if it ends with ok
gyp info it worked if it ends with ok
gyp info using node-gyp@3.8.0
gyp info using node@11.4.0 | linux | arm
gyp info using node-gyp@3.8.0
gyp info using node@11.4.0 | linux | arm
gyp infogyp info  spawn /usr/bin/python2
spawn /usr/bin/python2
gypgyp  infoinfo  spawn argsspawn args [ '/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
 [ '/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
gypgyp info spawn args   'binding.gyp',
gyp info  info spawn args   'binding.gyp',
gyp spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/home/pi/hekkie/node_modules/serialport/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp infoinfo  spawn args   '/home/pi/hekkie/node_modules/serialport/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/usr/local/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/usr/local/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/pi/.node-gyp/11.4.0/include/node/common.gypi',
gyp spawn argsinfo   '/home/pi/.node-gyp/11.4.0/include/node/common.gypi',
 gypspawn args   '-Dlibrary=shared_library',
gyp info  info spawn args   '-Dvisibility=default',
gypspawn args   '-Dlibrary=shared_library',
gyp  infoinfo  spawn argsspawn args   '-Dvisibility=default',
gyp info    '-Dnode_root_dir=/home/pi/.node-gyp/11.4.0',
gyp infospawn args    '-Dnode_root_dir=/home/pi/.node-gyp/11.4.0',
spawn argsgyp info spawn args   '-Dnode_gyp_dir=/usr/local/lib/node_modules/npm/node_modules/node-gyp',
gyp info spawn args   '-Dnode_gyp_dir=/usr/local/lib/node_modules/npm/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/home/pi/.node-gyp/11.4.0/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/home/pi/hekkie/node_modules/serialport',
gyp info   '-Dnode_lib_file=/home/pi/.node-gyp/11.4.0/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/home/pi/hekkie/node_modules/serialport',
gyp info  spawn argsspawn args   '-Dnode_engine=v8',
   '-Dnode_engine=v8',
gypgyp  infoinfo  spawn argsspawn args   '--depth=.',
   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp info ok 
gyp info ok 
gyp info it worked if it ends with ok
gypgyp info using node-gyp@3.8.0
 gyp info infousing node@11.4.0 | linux | arm
 it worked if it ends with ok
gyp info using node-gyp@3.8.0
gyp info using node@11.4.0 | linux | arm
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
make: Entering directory '/home/pi/hekkie/node_modules/serialport/build'
  CXX(target) Release/obj.target/serialport/src/serialport.o
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
make: Entering directory '/home/pi/hekkie/node_modules/serialport/build'
  CXX(target) Release/obj.target/serialport/src/serialport.o
In file included from ../src/./serialport.h:6:0,
                 from ../src/serialport.cpp:1:
../../nan/nan.h: In constructor 'Nan::Utf8String::Utf8String(v8::Local<v8::Value>)':
../../nan/nan.h:1064:78: warning: 'v8::Local<v8::String> v8::Value::ToString(v8::Isolate*) const' is deprecated: Use maybe version [-Wdeprecated-declarations]
       v8::Local<v8::String> string = from->ToString(v8::Isolate::GetCurrent());
                                                                              ^
In file included from /home/pi/.node-gyp/11.4.0/include/node/v8.h:26:0,
                 from /home/pi/.node-gyp/11.4.0/include/node/node.h:63,
                 from ../../nan/nan.h:52,
                 from ../src/./serialport.h:6,
                 from ../src/serialport.cpp:1:
/home/pi/.node-gyp/11.4.0/include/node/v8.h:2538:31: note: declared here
                 Local<String> ToString(Isolate* isolate) const);
                               ^
/home/pi/.node-gyp/11.4.0/include/node/v8config.h:326:3: note: in definition of macro 'V8_DEPRECATED'
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
In file included from ../src/./serialport.h:6:0,
                 from ../src/serialport.cpp:1:
../../nan/nan.h: In constructor 'Nan::Utf8String::Utf8String(v8::Local<v8::Value>)':
../../nan/nan.h:1064:78: warning: 'v8::Local<v8::String> v8::Value::ToString(v8::Isolate*) const' is deprecated: Use maybe version [-Wdeprecated-declarations]
       v8::Local<v8::String> string = from->ToString(v8::Isolate::GetCurrent());
                                                                              ^
In file included from /home/pi/.node-gyp/11.4.0/include/node/v8.h:26:0,
                 from /home/pi/.node-gyp/11.4.0/include/node/node.h:63,
                 from ../../nan/nan.h:52,
                 from ../src/./serialport.h:6,
                 from ../src/serialport.cpp:1:
/home/pi/.node-gyp/11.4.0/include/node/v8.h:2538:31: note: declared here
                 Local<String> ToString(Isolate* isolate) const);
                               ^
/home/pi/.node-gyp/11.4.0/include/node/v8config.h:326:3: note: in definition of macro 'V8_DEPRECATED'
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
../src/serialport.cpp: In function 'Nan::NAN_METHOD_RETURN_TYPE Open(Nan::NAN_METHOD_ARGS_TYPE)':
../src/serialport.cpp:41:48: warning: 'v8::Local<v8::String> v8::Value::ToString() const' is deprecated: Use maybe version [-Wdeprecated-declarations]
   v8::String::Utf8Value path(info[0]->ToString());
                                                ^
In file included from /home/pi/.node-gyp/11.4.0/include/node/node.h:63:0,
                 from ../../nan/nan.h:52,
                 from ../src/./serialport.h:6,
                 from ../src/serialport.cpp:1:
/home/pi/.node-gyp/11.4.0/include/node/v8.h:10248:15: note: declared here
 Local<String> Value::ToString() const {
               ^~~~~
../src/serialport.cpp:41:49: warning: 'v8::String::Utf8Value::Utf8Value(v8::Local<v8::Value>)' is deprecated: Use Isolate version [-Wdeprecated-declarations]
   v8::String::Utf8Value path(info[0]->ToString());
                                                 ^
../src/serialport.cpp: In function 'Nan::NAN_METHOD_RETURN_TYPE Open(Nan::NAN_METHOD_ARGS_TYPE)':
../src/serialport.cpp:41:48: warning: 'v8::Local<v8::String> v8::Value::ToString() const' is deprecated: Use maybe version [-Wdeprecated-declarations]
   v8::String::Utf8Value path(info[0]->ToString());
                                                ^
In file included from /home/pi/.node-gyp/11.4.0/include/node/v8.h:26:0,
                 from /home/pi/.node-gyp/11.4.0/include/node/node.h:63,
                 from ../../nan/nan.h:52,
                 from ../src/./serialport.h:6,
                 from ../src/serialport.cpp:1:
/home/pi/.node-gyp/11.4.0/include/node/v8.h:2992:28: note: declared here
                   explicit Utf8Value(Local<v8::Value> obj));
                            ^
/home/pi/.node-gyp/11.4.0/include/node/v8config.h:326:3: note: in definition of macro 'V8_DEPRECATED'
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
../src/serialport.cpp:48:53: warning: 'v8::Local<v8::Object> v8::Value::ToObject() const' is deprecated: Use maybe version [-Wdeprecated-declarations]
   v8::Local<v8::Object> options = info[1]->ToObject();
                                                     ^
In file included from /home/pi/.node-gyp/11.4.0/include/node/node.h:63:0,
                 from ../../nan/nan.h:52,
                 from ../src/./serialport.h:6,
                 from ../src/serialport.cpp:1:
/home/pi/.node-gyp/11.4.0/include/node/v8.h:10254:15: note: declared here
 Local<Object> Value::ToObject() const {
               ^~~~~
In file included from /home/pi/.node-gyp/11.4.0/include/node/node.h:63:0,
                 from ../../nan/nan.h:52,
                 from ../src/./serialport.h:6,
                 from ../src/serialport.cpp:1:
/home/pi/.node-gyp/11.4.0/include/node/v8.h:10248:15: note: declared here
 Local<String> Value::ToString() const {
               ^~~~~
../src/serialport.cpp:41:49: warning: 'v8::String::Utf8Value::Utf8Value(v8::Local<v8::Value>)' is deprecated: Use Isolate version [-Wdeprecated-declarations]
   v8::String::Utf8Value path(info[0]->ToString());
                                                 ^
In file included from /home/pi/.node-gyp/11.4.0/include/node/v8.h:26:0,
                 from /home/pi/.node-gyp/11.4.0/include/node/node.h:63,
                 from ../../nan/nan.h:52,
                 from ../src/./serialport.h:6,
                 from ../src/serialport.cpp:1:
/home/pi/.node-gyp/11.4.0/include/node/v8.h:2992:28: note: declared here
                   explicit Utf8Value(Local<v8::Value> obj));
                            ^
/home/pi/.node-gyp/11.4.0/include/node/v8config.h:326:3: note: in definition of macro 'V8_DEPRECATED'
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
../src/serialport.cpp:48:53: warning: 'v8::Local<v8::Object> v8::Value::ToObject() const' is deprecated: Use maybe version [-Wdeprecated-declarations]
   v8::Local<v8::Object> options = info[1]->ToObject();
                                                     ^
In file included from /home/pi/.node-gyp/11.4.0/include/node/node.h:63:0,
                 from ../../nan/nan.h:52,
                 from ../src/./serialport.h:6,
                 from ../src/serialport.cpp:1:
/home/pi/.node-gyp/11.4.0/include/node/v8.h:10254:15: note: declared here
 Local<Object> Value::ToObject() const {
               ^~~~~
../src/serialport.cpp: In function 'void EIO_AfterOpen(uv_work_t*)':
../src/serialport.cpp:96:30: warning: 'v8::Local<v8::Value> Nan::Callback::Call(int, v8::Local<v8::Value>*) const' is deprecated [-Wdeprecated-declarations]
   data->callback.Call(2, argv);
                              ^
In file included from ../src/./serialport.h:6:0,
                 from ../src/serialport.cpp:1:
../../nan/nan.h:1655:3: note: declared here
   Call(int argc, v8::Local<v8::Value> argv[]) const {
   ^~~~
../src/serialport.cpp: In function 'void EIO_AfterOpen(uv_work_t*)':
../src/serialport.cpp:96:30: warning: 'v8::Local<v8::Value> Nan::Callback::Call(int, v8::Local<v8::Value>*) const' is deprecated [-Wdeprecated-declarations]
   data->callback.Call(2, argv);
                              ^
../src/serialport.cpp: In function 'Nan::NAN_METHOD_RETURN_TYPE Update(Nan::NAN_METHOD_ARGS_TYPE)':
../src/serialport.cpp:114:53: warning: 'v8::Local<v8::Object> v8::Value::ToObject() const' is deprecated: Use maybe version [-Wdeprecated-declarations]
   v8::Local<v8::Object> options = info[1]->ToObject();
                                                     ^
In file included from /home/pi/.node-gyp/11.4.0/include/node/node.h:63:0,
                 from ../../nan/nan.h:52,
                 from ../src/./serialport.h:6,
                 from ../src/serialport.cpp:1:
/home/pi/.node-gyp/11.4.0/include/node/v8.h:10254:15: note: declared here
 Local<Object> Value::ToObject() const {
               ^~~~~
In file included from ../src/./serialport.h:6:0,
                 from ../src/serialport.cpp:1:
../../nan/nan.h:1655:3: note: declared here
   Call(int argc, v8::Local<v8::Value> argv[]) const {
   ^~~~
../src/serialport.cpp: In function 'Nan::NAN_METHOD_RETURN_TYPE Update(Nan::NAN_METHOD_ARGS_TYPE)':
../src/serialport.cpp:114:53: warning: 'v8::Local<v8::Object> v8::Value::ToObject() const' is deprecated: Use maybe version [-Wdeprecated-declarations]
   v8::Local<v8::Object> options = info[1]->ToObject();
                                                     ^
In file included from /home/pi/.node-gyp/11.4.0/include/node/node.h:63:0,
                 from ../../nan/nan.h:52,
                 from ../src/./serialport.h:6,
                 from ../src/serialport.cpp:1:
/home/pi/.node-gyp/11.4.0/include/node/v8.h:10254:15: note: declared here
 Local<Object> Value::ToObject() const {
               ^~~~~
../src/serialport.cpp: In function 'void EIO_AfterUpdate(uv_work_t*)':
../src/serialport.cpp:152:30: warning: 'v8::Local<v8::Value> Nan::Callback::Call(int, v8::Local<v8::Value>*) const' is deprecated [-Wdeprecated-declarations]
   data->callback.Call(1, argv);
                              ^
In file included from ../src/./serialport.h:6:0,
                 from ../src/serialport.cpp:1:
../../nan/nan.h:1655:3: note: declared here
   Call(int argc, v8::Local<v8::Value> argv[]) const {
   ^~~~
../src/serialport.cpp: In function 'void EIO_AfterUpdate(uv_work_t*)':
../src/serialport.cpp:152:30: warning: 'v8::Local<v8::Value> Nan::Callback::Call(int, v8::Local<v8::Value>*) const' is deprecated [-Wdeprecated-declarations]
   data->callback.Call(1, argv);
                              ^
In file included from ../src/./serialport.h:6:0,
                 from ../src/serialport.cpp:1:
../../nan/nan.h:1655:3: note: declared here
   Call(int argc, v8::Local<v8::Value> argv[]) const {
   ^~~~
../src/serialport.cpp: In function 'void EIO_AfterClose(uv_work_t*)':
../src/serialport.cpp:191:30: warning: 'v8::Local<v8::Value> Nan::Callback::Call(int, v8::Local<v8::Value>*) const' is deprecated [-Wdeprecated-declarations]
   data->callback.Call(1, argv);
                              ^
In file included from ../src/./serialport.h:6:0,
                 from ../src/serialport.cpp:1:
../../nan/nan.h:1655:3: note: declared here
   Call(int argc, v8::Local<v8::Value> argv[]) const {
   ^~~~
../src/serialport.cpp: In function 'void EIO_AfterClose(uv_work_t*)':
../src/serialport.cpp:191:30: warning: 'v8::Local<v8::Value> Nan::Callback::Call(int, v8::Local<v8::Value>*) const' is deprecated [-Wdeprecated-declarations]
   data->callback.Call(1, argv);
                              ^
In file included from ../src/./serialport.h:6:0,
                 from ../src/serialport.cpp:1:
../../nan/nan.h:1655:3: note: declared here
   Call(int argc, v8::Local<v8::Value> argv[]) const {
   ^~~~
../src/serialport.cpp: In function 'void EIO_AfterFlush(uv_work_t*)':
../src/serialport.cpp:235:30: warning: 'v8::Local<v8::Value> Nan::Callback::Call(int, v8::Local<v8::Value>*) const' is deprecated [-Wdeprecated-declarations]
   data->callback.Call(1, argv);
                              ^
In file included from ../src/./serialport.h:6:0,
                 from ../src/serialport.cpp:1:
../../nan/nan.h:1655:3: note: declared here
   Call(int argc, v8::Local<v8::Value> argv[]) const {
   ^~~~
../src/serialport.cpp: In function 'void EIO_AfterFlush(uv_work_t*)':
../src/serialport.cpp:235:30: warning: 'v8::Local<v8::Value> Nan::Callback::Call(int, v8::Local<v8::Value>*) const' is deprecated [-Wdeprecated-declarations]
   data->callback.Call(1, argv);
                              ^
../src/serialport.cpp: In function 'Nan::NAN_METHOD_RETURN_TYPE Set(Nan::NAN_METHOD_ARGS_TYPE)':
../src/serialport.cpp:254:53: warning: 'v8::Local<v8::Object> v8::Value::ToObject() const' is deprecated: Use maybe version [-Wdeprecated-declarations]
   v8::Local<v8::Object> options = info[1]->ToObject();
                                                     ^
In file included from /home/pi/.node-gyp/11.4.0/include/node/node.h:63:0,
                 from ../../nan/nan.h:52,
                 from ../src/./serialport.h:6,
                 from ../src/serialport.cpp:1:
/home/pi/.node-gyp/11.4.0/include/node/v8.h:10254:15: note: declared here
 Local<Object> Value::ToObject() const {
               ^~~~~
In file included from ../src/./serialport.h:6:0,
                 from ../src/serialport.cpp:1:
../../nan/nan.h:1655:3: note: declared here
   Call(int argc, v8::Local<v8::Value> argv[]) const {
   ^~~~
../src/serialport.cpp: In function 'Nan::NAN_METHOD_RETURN_TYPE Set(Nan::NAN_METHOD_ARGS_TYPE)':
../src/serialport.cpp:254:53: warning: 'v8::Local<v8::Object> v8::Value::ToObject() const' is deprecated: Use maybe version [-Wdeprecated-declarations]
   v8::Local<v8::Object> options = info[1]->ToObject();
                                                     ^
In file included from /home/pi/.node-gyp/11.4.0/include/node/node.h:63:0,
                 from ../../nan/nan.h:52,
                 from ../src/./serialport.h:6,
                 from ../src/serialport.cpp:1:
/home/pi/.node-gyp/11.4.0/include/node/v8.h:10254:15: note: declared here
 Local<Object> Value::ToObject() const {
               ^~~~~
../src/serialport.cpp: In function 'void EIO_AfterSet(uv_work_t*)':
../src/serialport.cpp:290:30: warning: 'v8::Local<v8::Value> Nan::Callback::Call(int, v8::Local<v8::Value>*) const' is deprecated [-Wdeprecated-declarations]
   data->callback.Call(1, argv);
                              ^
In file included from ../src/./serialport.h:6:0,
                 from ../src/serialport.cpp:1:
../../nan/nan.h:1655:3: note: declared here
   Call(int argc, v8::Local<v8::Value> argv[]) const {
   ^~~~
../src/serialport.cpp: In function 'void EIO_AfterSet(uv_work_t*)':
../src/serialport.cpp:290:30: warning: 'v8::Local<v8::Value> Nan::Callback::Call(int, v8::Local<v8::Value>*) const' is deprecated [-Wdeprecated-declarations]
   data->callback.Call(1, argv);
                              ^
In file included from ../src/./serialport.h:6:0,
                 from ../src/serialport.cpp:1:
../../nan/nan.h:1655:3: note: declared here
   Call(int argc, v8::Local<v8::Value> argv[]) const {
   ^~~~
../src/serialport.cpp: In function 'void EIO_AfterGet(uv_work_t*)':
../src/serialport.cpp:342:30: warning: 'v8::Local<v8::Value> Nan::Callback::Call(int, v8::Local<v8::Value>*) const' is deprecated [-Wdeprecated-declarations]
   data->callback.Call(2, argv);
                              ^
In file included from ../src/./serialport.h:6:0,
                 from ../src/serialport.cpp:1:
../../nan/nan.h:1655:3: note: declared here
   Call(int argc, v8::Local<v8::Value> argv[]) const {
   ^~~~
../src/serialport.cpp: In function 'void EIO_AfterGet(uv_work_t*)':
../src/serialport.cpp:342:30: warning: 'v8::Local<v8::Value> Nan::Callback::Call(int, v8::Local<v8::Value>*) const' is deprecated [-Wdeprecated-declarations]
   data->callback.Call(2, argv);
                              ^
In file included from ../src/./serialport.h:6:0,
                 from ../src/serialport.cpp:1:
../../nan/nan.h:1655:3: note: declared here
   Call(int argc, v8::Local<v8::Value> argv[]) const {
   ^~~~
../src/serialport.cpp: In function 'void EIO_AfterDrain(uv_work_t*)':
../src/serialport.cpp:384:30: warning: 'v8::Local<v8::Value> Nan::Callback::Call(int, v8::Local<v8::Value>*) const' is deprecated [-Wdeprecated-declarations]
   data->callback.Call(1, argv);
                              ^
In file included from ../src/./serialport.h:6:0,
                 from ../src/serialport.cpp:1:
../../nan/nan.h:1655:3: note: declared here
   Call(int argc, v8::Local<v8::Value> argv[]) const {
   ^~~~
../src/serialport.cpp: In function 'void EIO_AfterDrain(uv_work_t*)':
../src/serialport.cpp:384:30: warning: 'v8::Local<v8::Value> Nan::Callback::Call(int, v8::Local<v8::Value>*) const' is deprecated [-Wdeprecated-declarations]
   data->callback.Call(1, argv);
                              ^
In file included from ../src/./serialport.h:6:0,
                 from ../src/serialport.cpp:1:
../../nan/nan.h:1655:3: note: declared here
   Call(int argc, v8::Local<v8::Value> argv[]) const {
   ^~~~
sed: can't read ./Release/.deps/Release/obj.target/serialport/src/serialport.o.d.raw: No such file or directory
  CXX(target) Release/obj.target/serialport/src/serialport_unix.o
rm: cannot remove './Release/.deps/Release/obj.target/serialport/src/serialport.o.d.raw': No such file or directory
serialport.target.mk:101: recipe for target 'Release/obj.target/serialport/src/serialport.o' failed
make: *** [Release/obj.target/serialport/src/serialport.o] Error 1
make: Leaving directory '/home/pi/hekkie/node_modules/serialport/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:189:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:254:12)
gyp ERR! System Linux 4.14.79+
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/home/pi/hekkie/node_modules/serialport/build/Release/serialport.node" "--module_name=serialport" "--module_path=/home/pi/hekkie/node_modules/serialport/build/Release"
gyp ERR! cwd /home/pi/hekkie/node_modules/serialport
gyp ERR! node -v v11.4.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/home/pi/hekkie/node_modules/serialport/build/Release/serialport.node --module_name=serialport --module_path=/home/pi/hekkie/node_modules/serialport/build/Release' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/home/pi/hekkie/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:189:13)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:978:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:265:5)
node-pre-gyp ERR! System Linux 4.14.79+
node-pre-gyp ERR! command "/usr/local/bin/node" "/home/pi/hekkie/node_modules/serialport/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /home/pi/hekkie/node_modules/serialport
node-pre-gyp ERR! node -v v11.4.0
node-pre-gyp ERR! node-pre-gyp -v v0.6.39
node-pre-gyp ERR! not ok 
Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/home/pi/hekkie/node_modules/serialport/build/Release/serialport.node --module_name=serialport --module_path=/home/pi/hekkie/node_modules/serialport/build/Release' (1)
In file included from ../src/./serialport.h:6:0,
                 from ../src/serialport_unix.cpp:2:
../../nan/nan.h: In constructor 'Nan::Utf8String::Utf8String(v8::Local<v8::Value>)':
../../nan/nan.h:1064:78: warning: 'v8::Local<v8::String> v8::Value::ToString(v8::Isolate*) const' is deprecated: Use maybe version [-Wdeprecated-declarations]
       v8::Local<v8::String> string = from->ToString(v8::Isolate::GetCurrent());
                                                                              ^
In file included from /home/pi/.node-gyp/11.4.0/include/node/v8.h:26:0,
                 from /home/pi/.node-gyp/11.4.0/include/node/node.h:63,
                 from ../../nan/nan.h:52,
                 from ../src/./serialport.h:6,
                 from ../src/serialport_unix.cpp:2:
/home/pi/.node-gyp/11.4.0/include/node/v8.h:2538:31: note: declared here
                 Local<String> ToString(Isolate* isolate) const);
                               ^
/home/pi/.node-gyp/11.4.0/include/node/v8config.h:326:3: note: in definition of macro 'V8_DEPRECATED'
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
  CXX(target) Release/obj.target/serialport/src/poller.o
In file included from ../src/poller.cpp:1:0:
../../nan/nan.h: In constructor 'Nan::Utf8String::Utf8String(v8::Local<v8::Value>)':
../../nan/nan.h:1064:78: warning: 'v8::Local<v8::String> v8::Value::ToString(v8::Isolate*) const' is deprecated: Use maybe version [-Wdeprecated-declarations]
       v8::Local<v8::String> string = from->ToString(v8::Isolate::GetCurrent());
                                                                              ^
In file included from /home/pi/.node-gyp/11.4.0/include/node/v8.h:26:0,
                 from /home/pi/.node-gyp/11.4.0/include/node/node.h:63,
                 from ../../nan/nan.h:52,
                 from ../src/poller.cpp:1:
/home/pi/.node-gyp/11.4.0/include/node/v8.h:2538:31: note: declared here
                 Local<String> ToString(Isolate* isolate) const);
                               ^
/home/pi/.node-gyp/11.4.0/include/node/v8config.h:326:3: note: in definition of macro 'V8_DEPRECATED'
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
../src/poller.cpp: In static member function 'static void Poller::onData(uv_poll_t*, int, int)':
../src/poller.cpp:69:29: warning: 'v8::Local<v8::Value> Nan::Callback::Call(int, v8::Local<v8::Value>*) const' is deprecated [-Wdeprecated-declarations]
   obj->callback.Call(2, argv);
                             ^
In file included from ../src/poller.cpp:1:0:
../../nan/nan.h:1655:3: note: declared here
   Call(int argc, v8::Local<v8::Value> argv[]) const {
   ^~~~
  SOLINK_MODULE(target) Release/obj.target/serialport.node
  COPY Release/serialport.node
make: Leaving directory '/home/pi/hekkie/node_modules/serialport/build'
gyp info ok
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

Adding resolutions to the package.json file allows to install but does not seem to work properly (I'm looking in to that).

**Comment by tschiemer** [comment]
Hi! I just made a short install test on osx 10.12 using both yarn 1.10.1 and npm 6.4.1 (node 10.8.0) and yes the build of the serialport dependency failed in both runs.

The current version of at-commander is dependent on serialport 5.0.0, which worked at the time. Trying to install/build serialport 5.0.0 only will fail the same way for me.

The current version of serialport 7.1.0 might indeed have some breaking changes so simply using that instead of the older version might not work.

If you're looking into that I won't say no :)

**Comment by DJFliX** [comment]
I tested with the latest v6 of serialport and that seemed to work. Unfortunately there does not seem to be some kind of test suite in this project or something so I'm not sure you should take my word for it... Probably the best thing to do is just try it I guess?

**Comment by tschiemer** [comment]
Heja! Many thanks for testing. Alas, testing would be the best thing or otherwise checking if the signature/behaviour of the used serialport functions have changed.

True, a test suite would indeed be good. Not sure when I find the time to take care of it..
